services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-service
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "7432:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10